spring:
  application:
    name: session-login
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:test;MODE=MYSQL"
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      encoding: UTF-8
      mode: always

server:
  servlet:
    encoding:
      force-response: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG