apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: ingress-marvel-heroes
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: k8s-worker-01
    http: 
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: svc-marvel
              port:
                number: 80
  - host: k8s-worker-02
    http: 
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: svc-thor
              port:
                number: 80