apiVersion: v1
kind: Pod
metadata:
  name: pod-appjs
  labels:
    app: web
    # version: "1.14"
    version: "1.15"
spec:
  containers:
    - name: appjs-container
      image: smlinux/appjs
      ports:
        - containerPort: 8080