apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx
spec:
  # replicas: 3
  replicas: 2
  selector:
    app: web
    version: "1.14"
  template:
    metadata:
      name: pod-nginx
      labels:
        app: web
        version: "1.14"
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.14
          ports:
            - containerPort: 80